using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Text;

namespace DBAdminPanel.SourceGenerator.Generators
{
    internal static class JsonConverterGenerator
    {
        public static void Generate(GeneratorExecutionContext context)
        {
            var sb = new StringBuilder();
            sb.AppendLine("using System.Text.Json;");
            sb.AppendLine("using System.Text.Json.Serialization;");
            sb.AppendLine();
            sb.AppendLine("namespace DBAdminPanel.Generated.Controllers");
            sb.AppendLine("{");
            sb.AppendLine("    public class StringToNumberConverter : JsonConverterFactory");
            sb.AppendLine("    {");
            sb.AppendLine("        public override bool CanConvert(Type typeToConvert)");
            sb.AppendLine("        {");
            sb.AppendLine("            return typeToConvert == typeof(decimal) || typeToConvert == typeof(decimal?) ||");
            sb.AppendLine("                   typeToConvert == typeof(double) || typeToConvert == typeof(double?) ||");
            sb.AppendLine("                   typeToConvert == typeof(float) || typeToConvert == typeof(float?) ||");
            sb.AppendLine("                   typeToConvert == typeof(int) || typeToConvert == typeof(int?) ||");
            sb.AppendLine("                   typeToConvert == typeof(long) || typeToConvert == typeof(long?);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public override JsonConverter CreateConverter(Type typeToConvert, JsonSerializerOptions options)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (typeToConvert == typeof(decimal) || typeToConvert == typeof(decimal?))");
            sb.AppendLine("                return new DecimalConverter();");
            sb.AppendLine("            if (typeToConvert == typeof(double) || typeToConvert == typeof(double?))");
            sb.AppendLine("                return new DoubleConverter();");
            sb.AppendLine("            if (typeToConvert == typeof(float) || typeToConvert == typeof(float?))");
            sb.AppendLine("                return new FloatConverter();");
            sb.AppendLine("            if (typeToConvert == typeof(int) || typeToConvert == typeof(int?))");
            sb.AppendLine("                return new IntConverter();");
            sb.AppendLine("            if (typeToConvert == typeof(long) || typeToConvert == typeof(long?))");
            sb.AppendLine("                return new LongConverter();");
            sb.AppendLine("            throw new NotSupportedException();");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private class DecimalConverter : JsonConverter<decimal>");
            sb.AppendLine("        {");
            sb.AppendLine("            public override decimal Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)");
            sb.AppendLine("            {");
            sb.AppendLine("                if (reader.TokenType == JsonTokenType.String)");
            sb.AppendLine("                {");
            sb.AppendLine("                    var str = reader.GetString();");
            sb.AppendLine("                    if (string.IsNullOrWhiteSpace(str)) return 0m;");
            sb.AppendLine("                    return decimal.Parse(str, System.Globalization.CultureInfo.InvariantCulture);");
            sb.AppendLine("                }");
            sb.AppendLine("                return reader.GetDecimal();");
            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine("            public override void Write(Utf8JsonWriter writer, decimal value, JsonSerializerOptions options)");
            sb.AppendLine("            {");
            sb.AppendLine("                writer.WriteNumberValue(value);");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private class DoubleConverter : JsonConverter<double>");
            sb.AppendLine("        {");
            sb.AppendLine("            public override double Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)");
            sb.AppendLine("            {");
            sb.AppendLine("                if (reader.TokenType == JsonTokenType.String)");
            sb.AppendLine("                {");
            sb.AppendLine("                    var str = reader.GetString();");
            sb.AppendLine("                    if (string.IsNullOrWhiteSpace(str)) return 0.0;");
            sb.AppendLine("                    return double.Parse(str, System.Globalization.CultureInfo.InvariantCulture);");
            sb.AppendLine("                }");
            sb.AppendLine("                return reader.GetDouble();");
            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine("            public override void Write(Utf8JsonWriter writer, double value, JsonSerializerOptions options)");
            sb.AppendLine("            {");
            sb.AppendLine("                writer.WriteNumberValue(value);");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private class FloatConverter : JsonConverter<float>");
            sb.AppendLine("        {");
            sb.AppendLine("            public override float Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)");
            sb.AppendLine("            {");
            sb.AppendLine("                if (reader.TokenType == JsonTokenType.String)");
            sb.AppendLine("                {");
            sb.AppendLine("                    var str = reader.GetString();");
            sb.AppendLine("                    if (string.IsNullOrWhiteSpace(str)) return 0f;");
            sb.AppendLine("                    return float.Parse(str, System.Globalization.CultureInfo.InvariantCulture);");
            sb.AppendLine("                }");
            sb.AppendLine("                return reader.GetSingle();");
            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine("            public override void Write(Utf8JsonWriter writer, float value, JsonSerializerOptions options)");
            sb.AppendLine("            {");
            sb.AppendLine("                writer.WriteNumberValue(value);");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private class IntConverter : JsonConverter<int>");
            sb.AppendLine("        {");
            sb.AppendLine("            public override int Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)");
            sb.AppendLine("            {");
            sb.AppendLine("                if (reader.TokenType == JsonTokenType.String)");
            sb.AppendLine("                {");
            sb.AppendLine("                    var str = reader.GetString();");
            sb.AppendLine("                    if (string.IsNullOrWhiteSpace(str)) return 0;");
            sb.AppendLine("                    return int.Parse(str, System.Globalization.CultureInfo.InvariantCulture);");
            sb.AppendLine("                }");
            sb.AppendLine("                return reader.GetInt32();");
            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine("            public override void Write(Utf8JsonWriter writer, int value, JsonSerializerOptions options)");
            sb.AppendLine("            {");
            sb.AppendLine("                writer.WriteNumberValue(value);");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private class LongConverter : JsonConverter<long>");
            sb.AppendLine("        {");
            sb.AppendLine("            public override long Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)");
            sb.AppendLine("            {");
            sb.AppendLine("                if (reader.TokenType == JsonTokenType.String)");
            sb.AppendLine("                {");
            sb.AppendLine("                    var str = reader.GetString();");
            sb.AppendLine("                    if (string.IsNullOrWhiteSpace(str)) return 0L;");
            sb.AppendLine("                    return long.Parse(str, System.Globalization.CultureInfo.InvariantCulture);");
            sb.AppendLine("                }");
            sb.AppendLine("                return reader.GetInt64();");
            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine("            public override void Write(Utf8JsonWriter writer, long value, JsonSerializerOptions options)");
            sb.AppendLine("            {");
            sb.AppendLine("                writer.WriteNumberValue(value);");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            context.AddSource("StringToNumberConverter.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }
    }
}


